/**
 * This class is generated by jOOQ
 */
package ru.amazing.bank.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bank extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 78242060;

	/**
	 * The reference instance of <code>bank</code>
	 */
	public static final Bank BANK = new Bank();

	/**
	 * No further instances allowed
	 */
	private Bank() {
		super("bank");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			ru.amazing.bank.jooq.tables.Account.ACCOUNT,
			ru.amazing.bank.jooq.tables.Bankaccount.BANKACCOUNT,
			ru.amazing.bank.jooq.tables.Bankcard.BANKCARD,
			ru.amazing.bank.jooq.tables.Person.PERSON,
			ru.amazing.bank.jooq.tables.Transaction.TRANSACTION);
	}
}
