/**
 * This class is generated by jOOQ
 */
package ru.amazing.bank.jooq;

/**
 * A class modelling foreign key relationships between tables of the <code>bank</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<ru.amazing.bank.jooq.tables.records.AccountRecord, java.lang.Integer> IDENTITY_ACCOUNT = Identities0.IDENTITY_ACCOUNT;
	public static final org.jooq.Identity<ru.amazing.bank.jooq.tables.records.BankaccountRecord, java.lang.Integer> IDENTITY_BANKACCOUNT = Identities0.IDENTITY_BANKACCOUNT;
	public static final org.jooq.Identity<ru.amazing.bank.jooq.tables.records.BankcardRecord, java.lang.Integer> IDENTITY_BANKCARD = Identities0.IDENTITY_BANKCARD;
	public static final org.jooq.Identity<ru.amazing.bank.jooq.tables.records.PersonRecord, java.lang.Integer> IDENTITY_PERSON = Identities0.IDENTITY_PERSON;
	public static final org.jooq.Identity<ru.amazing.bank.jooq.tables.records.TransactionRecord, java.lang.Integer> IDENTITY_TRANSACTION = Identities0.IDENTITY_TRANSACTION;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.AccountRecord> KEY_ACCOUNT_PRIMARY = UniqueKeys0.KEY_ACCOUNT_PRIMARY;
	public static final org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.BankaccountRecord> KEY_BANKACCOUNT_PRIMARY = UniqueKeys0.KEY_BANKACCOUNT_PRIMARY;
	public static final org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.BankcardRecord> KEY_BANKCARD_PRIMARY = UniqueKeys0.KEY_BANKCARD_PRIMARY;
	public static final org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.PersonRecord> KEY_PERSON_PRIMARY = UniqueKeys0.KEY_PERSON_PRIMARY;
	public static final org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.TransactionRecord> KEY_TRANSACTION_PRIMARY = UniqueKeys0.KEY_TRANSACTION_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.AccountRecord, ru.amazing.bank.jooq.tables.records.BankaccountRecord> ACCOUNT_IBFK_1 = ForeignKeys0.ACCOUNT_IBFK_1;
	public static final org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.BankaccountRecord, ru.amazing.bank.jooq.tables.records.PersonRecord> BANKACCOUNT_IBFK_1 = ForeignKeys0.BANKACCOUNT_IBFK_1;
	public static final org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.BankcardRecord, ru.amazing.bank.jooq.tables.records.BankaccountRecord> BANKCARD_IBFK_1 = ForeignKeys0.BANKCARD_IBFK_1;
	public static final org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.TransactionRecord, ru.amazing.bank.jooq.tables.records.BankcardRecord> TRANSACTION_IBFK_1 = ForeignKeys0.TRANSACTION_IBFK_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<ru.amazing.bank.jooq.tables.records.AccountRecord, java.lang.Integer> IDENTITY_ACCOUNT = createIdentity(ru.amazing.bank.jooq.tables.Account.ACCOUNT, ru.amazing.bank.jooq.tables.Account.ACCOUNT.ID);
		public static org.jooq.Identity<ru.amazing.bank.jooq.tables.records.BankaccountRecord, java.lang.Integer> IDENTITY_BANKACCOUNT = createIdentity(ru.amazing.bank.jooq.tables.Bankaccount.BANKACCOUNT, ru.amazing.bank.jooq.tables.Bankaccount.BANKACCOUNT.ID);
		public static org.jooq.Identity<ru.amazing.bank.jooq.tables.records.BankcardRecord, java.lang.Integer> IDENTITY_BANKCARD = createIdentity(ru.amazing.bank.jooq.tables.Bankcard.BANKCARD, ru.amazing.bank.jooq.tables.Bankcard.BANKCARD.ID);
		public static org.jooq.Identity<ru.amazing.bank.jooq.tables.records.PersonRecord, java.lang.Integer> IDENTITY_PERSON = createIdentity(ru.amazing.bank.jooq.tables.Person.PERSON, ru.amazing.bank.jooq.tables.Person.PERSON.ID);
		public static org.jooq.Identity<ru.amazing.bank.jooq.tables.records.TransactionRecord, java.lang.Integer> IDENTITY_TRANSACTION = createIdentity(ru.amazing.bank.jooq.tables.Transaction.TRANSACTION, ru.amazing.bank.jooq.tables.Transaction.TRANSACTION.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.AccountRecord> KEY_ACCOUNT_PRIMARY = createUniqueKey(ru.amazing.bank.jooq.tables.Account.ACCOUNT, ru.amazing.bank.jooq.tables.Account.ACCOUNT.ID);
		public static final org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.BankaccountRecord> KEY_BANKACCOUNT_PRIMARY = createUniqueKey(ru.amazing.bank.jooq.tables.Bankaccount.BANKACCOUNT, ru.amazing.bank.jooq.tables.Bankaccount.BANKACCOUNT.ID);
		public static final org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.BankcardRecord> KEY_BANKCARD_PRIMARY = createUniqueKey(ru.amazing.bank.jooq.tables.Bankcard.BANKCARD, ru.amazing.bank.jooq.tables.Bankcard.BANKCARD.ID);
		public static final org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.PersonRecord> KEY_PERSON_PRIMARY = createUniqueKey(ru.amazing.bank.jooq.tables.Person.PERSON, ru.amazing.bank.jooq.tables.Person.PERSON.ID);
		public static final org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.TransactionRecord> KEY_TRANSACTION_PRIMARY = createUniqueKey(ru.amazing.bank.jooq.tables.Transaction.TRANSACTION, ru.amazing.bank.jooq.tables.Transaction.TRANSACTION.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.AccountRecord, ru.amazing.bank.jooq.tables.records.BankaccountRecord> ACCOUNT_IBFK_1 = createForeignKey(ru.amazing.bank.jooq.Keys.KEY_BANKACCOUNT_PRIMARY, ru.amazing.bank.jooq.tables.Account.ACCOUNT, ru.amazing.bank.jooq.tables.Account.ACCOUNT.BANKACCOUNT);
		public static final org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.BankaccountRecord, ru.amazing.bank.jooq.tables.records.PersonRecord> BANKACCOUNT_IBFK_1 = createForeignKey(ru.amazing.bank.jooq.Keys.KEY_PERSON_PRIMARY, ru.amazing.bank.jooq.tables.Bankaccount.BANKACCOUNT, ru.amazing.bank.jooq.tables.Bankaccount.BANKACCOUNT.PERSON);
		public static final org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.BankcardRecord, ru.amazing.bank.jooq.tables.records.BankaccountRecord> BANKCARD_IBFK_1 = createForeignKey(ru.amazing.bank.jooq.Keys.KEY_BANKACCOUNT_PRIMARY, ru.amazing.bank.jooq.tables.Bankcard.BANKCARD, ru.amazing.bank.jooq.tables.Bankcard.BANKCARD.BANKACCOUNT);
		public static final org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.TransactionRecord, ru.amazing.bank.jooq.tables.records.BankcardRecord> TRANSACTION_IBFK_1 = createForeignKey(ru.amazing.bank.jooq.Keys.KEY_BANKCARD_PRIMARY, ru.amazing.bank.jooq.tables.Transaction.TRANSACTION, ru.amazing.bank.jooq.tables.Transaction.TRANSACTION.BANKCARD);
	}
}
