/**
 * This class is generated by jOOQ
 */
package ru.amazing.bank.jooq;

/**
 * Convenience access to all tables in bank
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table bank.account
	 */
	public static final ru.amazing.bank.jooq.tables.Account ACCOUNT = ru.amazing.bank.jooq.tables.Account.ACCOUNT;

	/**
	 * The table bank.bankaccount
	 */
	public static final ru.amazing.bank.jooq.tables.Bankaccount BANKACCOUNT = ru.amazing.bank.jooq.tables.Bankaccount.BANKACCOUNT;

	/**
	 * The table bank.bankcard
	 */
	public static final ru.amazing.bank.jooq.tables.Bankcard BANKCARD = ru.amazing.bank.jooq.tables.Bankcard.BANKCARD;

	/**
	 * The table bank.person
	 */
	public static final ru.amazing.bank.jooq.tables.Person PERSON = ru.amazing.bank.jooq.tables.Person.PERSON;

	/**
	 * The table bank.transaction
	 */
	public static final ru.amazing.bank.jooq.tables.Transaction TRANSACTION = ru.amazing.bank.jooq.tables.Transaction.TRANSACTION;
}
