/**
 * This class is generated by jOOQ
 */
package ru.amazing.bank.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRecord extends org.jooq.impl.UpdatableRecordImpl<ru.amazing.bank.jooq.tables.records.AccountRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 487348407;

	/**
	 * Setter for <code>bank.account.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>bank.account.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>bank.account.login</code>.
	 */
	public void setLogin(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>bank.account.login</code>.
	 */
	public java.lang.String getLogin() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>bank.account.bankAccount</code>.
	 */
	public void setBankaccount(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>bank.account.bankAccount</code>.
	 */
	public java.lang.Integer getBankaccount() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>bank.account.passwordHash</code>.
	 */
	public void setPasswordhash(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>bank.account.passwordHash</code>.
	 */
	public java.lang.String getPasswordhash() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return ru.amazing.bank.jooq.tables.Account.ACCOUNT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return ru.amazing.bank.jooq.tables.Account.ACCOUNT.LOGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return ru.amazing.bank.jooq.tables.Account.ACCOUNT.BANKACCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return ru.amazing.bank.jooq.tables.Account.ACCOUNT.PASSWORDHASH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLogin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getBankaccount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPasswordhash();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountRecord value2(java.lang.String value) {
		setLogin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountRecord value3(java.lang.Integer value) {
		setBankaccount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountRecord value4(java.lang.String value) {
		setPasswordhash(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AccountRecord
	 */
	public AccountRecord() {
		super(ru.amazing.bank.jooq.tables.Account.ACCOUNT);
	}

	/**
	 * Create a detached, initialised AccountRecord
	 */
	public AccountRecord(java.lang.Integer id, java.lang.String login, java.lang.Integer bankaccount, java.lang.String passwordhash) {
		super(ru.amazing.bank.jooq.tables.Account.ACCOUNT);

		setValue(0, id);
		setValue(1, login);
		setValue(2, bankaccount);
		setValue(3, passwordhash);
	}
}
