/**
 * This class is generated by jOOQ
 */
package ru.amazing.bank.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankcardRecord extends org.jooq.impl.UpdatableRecordImpl<ru.amazing.bank.jooq.tables.records.BankcardRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Boolean> {

	private static final long serialVersionUID = -643374692;

	/**
	 * Setter for <code>bank.bankcard.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>bank.bankcard.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>bank.bankcard.cardNumber</code>.
	 */
	public void setCardnumber(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>bank.bankcard.cardNumber</code>.
	 */
	public java.lang.String getCardnumber() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>bank.bankcard.bankAccount</code>.
	 */
	public void setBankaccount(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>bank.bankcard.bankAccount</code>.
	 */
	public java.lang.Integer getBankaccount() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>bank.bankcard.blocked</code>.
	 */
	public void setBlocked(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>bank.bankcard.blocked</code>.
	 */
	public java.lang.Boolean getBlocked() {
		return (java.lang.Boolean) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return ru.amazing.bank.jooq.tables.Bankcard.BANKCARD.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return ru.amazing.bank.jooq.tables.Bankcard.BANKCARD.CARDNUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return ru.amazing.bank.jooq.tables.Bankcard.BANKCARD.BANKACCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return ru.amazing.bank.jooq.tables.Bankcard.BANKCARD.BLOCKED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getCardnumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getBankaccount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getBlocked();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankcardRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankcardRecord value2(java.lang.String value) {
		setCardnumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankcardRecord value3(java.lang.Integer value) {
		setBankaccount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankcardRecord value4(java.lang.Boolean value) {
		setBlocked(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankcardRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.Boolean value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BankcardRecord
	 */
	public BankcardRecord() {
		super(ru.amazing.bank.jooq.tables.Bankcard.BANKCARD);
	}

	/**
	 * Create a detached, initialised BankcardRecord
	 */
	public BankcardRecord(java.lang.Integer id, java.lang.String cardnumber, java.lang.Integer bankaccount, java.lang.Boolean blocked) {
		super(ru.amazing.bank.jooq.tables.Bankcard.BANKCARD);

		setValue(0, id);
		setValue(1, cardnumber);
		setValue(2, bankaccount);
		setValue(3, blocked);
	}
}
