/**
 * This class is generated by jOOQ
 */
package ru.amazing.bank.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account extends org.jooq.impl.TableImpl<ru.amazing.bank.jooq.tables.records.AccountRecord> {

	private static final long serialVersionUID = 129381853;

	/**
	 * The reference instance of <code>bank.account</code>
	 */
	public static final ru.amazing.bank.jooq.tables.Account ACCOUNT = new ru.amazing.bank.jooq.tables.Account();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ru.amazing.bank.jooq.tables.records.AccountRecord> getRecordType() {
		return ru.amazing.bank.jooq.tables.records.AccountRecord.class;
	}

	/**
	 * The column <code>bank.account.id</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.AccountRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>bank.account.login</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.AccountRecord, java.lang.String> LOGIN = createField("login", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this, "");

	/**
	 * The column <code>bank.account.bankAccount</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.AccountRecord, java.lang.Integer> BANKACCOUNT = createField("bankAccount", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>bank.account.passwordHash</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.AccountRecord, java.lang.String> PASSWORDHASH = createField("passwordHash", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * Create a <code>bank.account</code> table reference
	 */
	public Account() {
		this("account", null);
	}

	/**
	 * Create an aliased <code>bank.account</code> table reference
	 */
	public Account(java.lang.String alias) {
		this(alias, ru.amazing.bank.jooq.tables.Account.ACCOUNT);
	}

	private Account(java.lang.String alias, org.jooq.Table<ru.amazing.bank.jooq.tables.records.AccountRecord> aliased) {
		this(alias, aliased, null);
	}

	private Account(java.lang.String alias, org.jooq.Table<ru.amazing.bank.jooq.tables.records.AccountRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, ru.amazing.bank.jooq.Bank.BANK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ru.amazing.bank.jooq.tables.records.AccountRecord, java.lang.Integer> getIdentity() {
		return ru.amazing.bank.jooq.Keys.IDENTITY_ACCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.AccountRecord> getPrimaryKey() {
		return ru.amazing.bank.jooq.Keys.KEY_ACCOUNT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.AccountRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.AccountRecord>>asList(ru.amazing.bank.jooq.Keys.KEY_ACCOUNT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.AccountRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.AccountRecord, ?>>asList(ru.amazing.bank.jooq.Keys.ACCOUNT_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ru.amazing.bank.jooq.tables.Account as(java.lang.String alias) {
		return new ru.amazing.bank.jooq.tables.Account(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ru.amazing.bank.jooq.tables.Account rename(java.lang.String name) {
		return new ru.amazing.bank.jooq.tables.Account(name, null);
	}
}
