/**
 * This class is generated by jOOQ
 */
package ru.amazing.bank.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bankcard extends org.jooq.impl.TableImpl<ru.amazing.bank.jooq.tables.records.BankcardRecord> {

	private static final long serialVersionUID = -160265649;

	/**
	 * The reference instance of <code>bank.bankcard</code>
	 */
	public static final ru.amazing.bank.jooq.tables.Bankcard BANKCARD = new ru.amazing.bank.jooq.tables.Bankcard();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ru.amazing.bank.jooq.tables.records.BankcardRecord> getRecordType() {
		return ru.amazing.bank.jooq.tables.records.BankcardRecord.class;
	}

	/**
	 * The column <code>bank.bankcard.id</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.BankcardRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>bank.bankcard.cardNumber</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.BankcardRecord, java.lang.String> CARDNUMBER = createField("cardNumber", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this, "");

	/**
	 * The column <code>bank.bankcard.bankAccount</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.BankcardRecord, java.lang.Integer> BANKACCOUNT = createField("bankAccount", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>bank.bankcard.blocked</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.BankcardRecord, java.lang.Boolean> BLOCKED = createField("blocked", org.jooq.impl.SQLDataType.BIT, this, "");

	/**
	 * Create a <code>bank.bankcard</code> table reference
	 */
	public Bankcard() {
		this("bankcard", null);
	}

	/**
	 * Create an aliased <code>bank.bankcard</code> table reference
	 */
	public Bankcard(java.lang.String alias) {
		this(alias, ru.amazing.bank.jooq.tables.Bankcard.BANKCARD);
	}

	private Bankcard(java.lang.String alias, org.jooq.Table<ru.amazing.bank.jooq.tables.records.BankcardRecord> aliased) {
		this(alias, aliased, null);
	}

	private Bankcard(java.lang.String alias, org.jooq.Table<ru.amazing.bank.jooq.tables.records.BankcardRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, ru.amazing.bank.jooq.Bank.BANK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ru.amazing.bank.jooq.tables.records.BankcardRecord, java.lang.Integer> getIdentity() {
		return ru.amazing.bank.jooq.Keys.IDENTITY_BANKCARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.BankcardRecord> getPrimaryKey() {
		return ru.amazing.bank.jooq.Keys.KEY_BANKCARD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.BankcardRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.BankcardRecord>>asList(ru.amazing.bank.jooq.Keys.KEY_BANKCARD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.BankcardRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.BankcardRecord, ?>>asList(ru.amazing.bank.jooq.Keys.BANKCARD_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ru.amazing.bank.jooq.tables.Bankcard as(java.lang.String alias) {
		return new ru.amazing.bank.jooq.tables.Bankcard(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ru.amazing.bank.jooq.tables.Bankcard rename(java.lang.String name) {
		return new ru.amazing.bank.jooq.tables.Bankcard(name, null);
	}
}
