/**
 * This class is generated by jOOQ
 */
package ru.amazing.bank.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bankaccount extends org.jooq.impl.TableImpl<ru.amazing.bank.jooq.tables.records.BankaccountRecord> {

	private static final long serialVersionUID = -1356901693;

	/**
	 * The reference instance of <code>bank.bankaccount</code>
	 */
	public static final ru.amazing.bank.jooq.tables.Bankaccount BANKACCOUNT = new ru.amazing.bank.jooq.tables.Bankaccount();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ru.amazing.bank.jooq.tables.records.BankaccountRecord> getRecordType() {
		return ru.amazing.bank.jooq.tables.records.BankaccountRecord.class;
	}

	/**
	 * The column <code>bank.bankaccount.id</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.BankaccountRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>bank.bankaccount.bankAccountNumber</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.BankaccountRecord, java.lang.Integer> BANKACCOUNTNUMBER = createField("bankAccountNumber", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>bank.bankaccount.person</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.BankaccountRecord, java.lang.Integer> PERSON = createField("person", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>bank.bankaccount</code> table reference
	 */
	public Bankaccount() {
		this("bankaccount", null);
	}

	/**
	 * Create an aliased <code>bank.bankaccount</code> table reference
	 */
	public Bankaccount(java.lang.String alias) {
		this(alias, ru.amazing.bank.jooq.tables.Bankaccount.BANKACCOUNT);
	}

	private Bankaccount(java.lang.String alias, org.jooq.Table<ru.amazing.bank.jooq.tables.records.BankaccountRecord> aliased) {
		this(alias, aliased, null);
	}

	private Bankaccount(java.lang.String alias, org.jooq.Table<ru.amazing.bank.jooq.tables.records.BankaccountRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, ru.amazing.bank.jooq.Bank.BANK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ru.amazing.bank.jooq.tables.records.BankaccountRecord, java.lang.Integer> getIdentity() {
		return ru.amazing.bank.jooq.Keys.IDENTITY_BANKACCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.BankaccountRecord> getPrimaryKey() {
		return ru.amazing.bank.jooq.Keys.KEY_BANKACCOUNT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.BankaccountRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.BankaccountRecord>>asList(ru.amazing.bank.jooq.Keys.KEY_BANKACCOUNT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.BankaccountRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.BankaccountRecord, ?>>asList(ru.amazing.bank.jooq.Keys.BANKACCOUNT_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ru.amazing.bank.jooq.tables.Bankaccount as(java.lang.String alias) {
		return new ru.amazing.bank.jooq.tables.Bankaccount(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ru.amazing.bank.jooq.tables.Bankaccount rename(java.lang.String name) {
		return new ru.amazing.bank.jooq.tables.Bankaccount(name, null);
	}
}
