/**
 * This class is generated by jOOQ
 */
package ru.amazing.bank.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transaction extends org.jooq.impl.TableImpl<ru.amazing.bank.jooq.tables.records.TransactionRecord> {

	private static final long serialVersionUID = -1229447771;

	/**
	 * The reference instance of <code>bank.transaction</code>
	 */
	public static final ru.amazing.bank.jooq.tables.Transaction TRANSACTION = new ru.amazing.bank.jooq.tables.Transaction();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ru.amazing.bank.jooq.tables.records.TransactionRecord> getRecordType() {
		return ru.amazing.bank.jooq.tables.records.TransactionRecord.class;
	}

	/**
	 * The column <code>bank.transaction.id</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.TransactionRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>bank.transaction.bankCard</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.TransactionRecord, java.lang.Integer> BANKCARD = createField("bankCard", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>bank.transaction.transactionDate</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.TransactionRecord, java.sql.Date> TRANSACTIONDATE = createField("transactionDate", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>bank.transaction.amount</code>.
	 */
	public final org.jooq.TableField<ru.amazing.bank.jooq.tables.records.TransactionRecord, java.lang.Integer> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>bank.transaction</code> table reference
	 */
	public Transaction() {
		this("transaction", null);
	}

	/**
	 * Create an aliased <code>bank.transaction</code> table reference
	 */
	public Transaction(java.lang.String alias) {
		this(alias, ru.amazing.bank.jooq.tables.Transaction.TRANSACTION);
	}

	private Transaction(java.lang.String alias, org.jooq.Table<ru.amazing.bank.jooq.tables.records.TransactionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Transaction(java.lang.String alias, org.jooq.Table<ru.amazing.bank.jooq.tables.records.TransactionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, ru.amazing.bank.jooq.Bank.BANK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ru.amazing.bank.jooq.tables.records.TransactionRecord, java.lang.Integer> getIdentity() {
		return ru.amazing.bank.jooq.Keys.IDENTITY_TRANSACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.TransactionRecord> getPrimaryKey() {
		return ru.amazing.bank.jooq.Keys.KEY_TRANSACTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.TransactionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ru.amazing.bank.jooq.tables.records.TransactionRecord>>asList(ru.amazing.bank.jooq.Keys.KEY_TRANSACTION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.TransactionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<ru.amazing.bank.jooq.tables.records.TransactionRecord, ?>>asList(ru.amazing.bank.jooq.Keys.TRANSACTION_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ru.amazing.bank.jooq.tables.Transaction as(java.lang.String alias) {
		return new ru.amazing.bank.jooq.tables.Transaction(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ru.amazing.bank.jooq.tables.Transaction rename(java.lang.String name) {
		return new ru.amazing.bank.jooq.tables.Transaction(name, null);
	}
}
